room_id: room-1
agents:
    sensors:
        - id: temp-1
          type: sensor
          class: temperature
          publish_interval_s: 2
    controllers:
        - id: controller-1
          type: controller
    actuators:
        - id: actuator-1
          type: actuator
          class: light
